control_stage_config:
  target: ToonCrafter.cldm.cldm.ControlNet
  params:
    use_checkpoint: True
    image_size: 32 # unused
    in_channels: 4
    hint_channels: 1
    model_channels: 320
    attention_resolutions: [ 4, 2, 1 ]
    num_res_blocks: 2
    channel_mult: [ 1, 2, 4, 4 ]
    num_head_channels: 64 # need to fix for flash-attn
    use_spatial_transformer: True
    use_linear_in_transformer: True
    transformer_depth: 1
    context_dim: 1024
    legacy: False
